#!/usr/bin/env bash
# Configure or installs a new Nginx server to redirect to another page

REDIR="\\\tlocation /redirect_me {\n\t\t return 301 Moved Permanently https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
SRC="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "30i $REDIR" $SRC
sudo service nginx restart
